/********************************************
 * root/layout.js 
*********************************************/
import "./globals.css";
import Link from "next/link";
import AuthButton from "./lib/AuthButton";


export const metadata = {
  title: "Root Page",
  description: "Generated by create next app",
  icons: {
    icon: '/rito.png', // these images should be inside the public folder
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* This is bootstrap */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossOrigin="anonymous"></link>
      </head>

      <body>
        <main>
          {/* this is the nav bar div */}
          <div>
            <AuthButton />
          </div>
          {children}
        </main>
      </body>

    </html>
  );
}


