/********************************************
 * root/layout.js 
*********************************************/
import "./globals.css";
import Link from "next/link";

// import { Geist, Geist_Mono } from "next/font/google";
// im not going to use this as this affects children

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Root Page",
  description: "Generated by create next app",
  icons: {
    icon: '/rito.png', // these images should be inside the public folder
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* This is bootstrap */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossOrigin="anonymous"></link>
      </head>

      <body>
        <main>
          {children}
        </main>
      </body>

    </html>
  );
}


//  {/* this is the navbar and should be on all child pages 
//           * Will only use this for testing */}
//         <nav className="navbar navbar-expand-lg bg-dark">
//           <div className="container-fluid">
//             <Link className="navbar-brand" href="/">Navbar</Link>
//             <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
//               <span className="navbar-toggler-icon"></span>
//             </button>
//             <div className="collapse navbar-collapse" id="navbarNav">
//               <ul className="navbar-nav">                
//                 <li className="nav-item">
//                   <a className="nav-link" href="temp">temp</a>
//                 </li>
//                 <li className="nav-item">
//                   <a className="nav-link" href="checkIn">checkin</a>
//                 </li>
//               </ul>
//             </div>
//           </div>
//         </nav>