/* root layout */
import "./globals.css"; 

// import { Geist, Geist_Mono } from "next/font/google";
// im not going to use this as this affects children

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Root Page",
  description: "Generated by create next app",
  icons: {
    icon: '/rito.png', // these images should be inside the public folder
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* This is bootstrap */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"></link>
      </head>

      <body>

        {/* this is the navbar and should be on all child pages */}
        <nav class="navbar bg-dark text-white">
          <div class="container-fluid">
            <span class="navbar-brand mb-0 h1">
              Navbar
            </span>
          </div>
        </nav>

        <main>{children}</main>

      </body>

    </html>
);}
